### ISSUE TITLE
Add option for default single private window

### ISSUE THREAD

**Issue by ghost** [kukawski/Open-in-selected-Incognito-window#1]
Hi,

Thank you for great extension. It helps me a lot. I don't understand why Firefox doesn't have this as built-in feature  `:-(`

May I ask if you could add this feature?

- Normally I use only one private window. So it would be great if you add option to just _"Open in private window"_. So if I have one window, it opens the link in that window. I don't need _"Open link in new private window"_.

Thank you,

**Comment by kukawski** [comment]
Thanks for your feedback :-)
Do I understand the feature request correctly - if you have just one private window open, instead of having the nested context menu entry, there should be just the "main" entry which opens the link in the existing window. Is that correct? I'll consider adding the option.

**Comment by ghost** [comment]
@kukawski,

Thank you for your reply. Yes, I mean I wish to use one private window only. So it would be great if you have this option:

- Show one context menu item _"Open in single private window"_ (or other phrase as you see fit).

- If there is no private window: open the link in new private window.

- If there are 1+ private windows: open the link in _any_ window that the extension sees. I understand that it's difficult to decide which window to pick. So it would be great if you just pick one of them. In daily use, I will limit myself to one single private window. So the extension will pick the right one for me.

**Comment by kukawski** [comment]
It took a while, but I've just published a new version of the extension.
The extension got an option that disables nesting if single private window exists. In other cases it still creates a nested list.
If no private window exists, I didn't add "Open link in new private window", because it would duplicate the built-in context menu entry.
So far, I also didn't add logic for choosing a window, if more than one private window exists. I will think about adding another option that just chooses last used private window, unless it's the current window. Need to check how much effort it is to track private window usage.
